# Generated by Django 4.2.19 on 2025-02-11 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0008_alter_task_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIWorker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('industry', models.CharField(max_length=255)),
                ('job_functions', models.JSONField()),
                ('execution_type', models.CharField(choices=[('fully_autonomous', 'Fully Autonomous'), ('rule_based', 'Rule-Based'), ('hybrid', 'Hybrid AI + Human')], max_length=50)),
                ('default_config', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessAIWorker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('configurations', models.JSONField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('disabled', 'Disabled')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_workers', to='business.aiemployer')),
                ('ai_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_workers.aiworker')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
