# Generated by Django 4.2.19 on 2025-02-11 17:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workers', '0002_aitask'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAITaskExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('execution_type', models.CharField(choices=[('fully_autonomous', 'Fully Autonomous'), ('rule_based', 'Rule-Based'), ('hybrid', 'Hybrid (AI + Human Approval)')], max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('ai_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='ai_workers.aitask')),
                ('business_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executed_tasks', to='ai_workers.businessaiworker')),
            ],
        ),
    ]
