# Generated by Django 4.2.19 on 2025-07-14 13:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workers', '0003_businessaitaskexecution'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIWorkerLearningRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('execution_id', models.CharField(max_length=255, unique=True)),
                ('task_name', models.CharField(max_length=255)),
                ('execution_status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('partial', 'Partial Success')], max_length=20)),
                ('execution_time', models.FloatField(help_text='Execution time in seconds')),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('strategy_used', models.CharField(choices=[('high_performance', 'High Performance'), ('balanced', 'Balanced'), ('rapid_processing', 'Rapid Processing'), ('custom', 'Custom Strategy')], max_length=50)),
                ('ai_model_used', models.CharField(blank=True, max_length=50, null=True)),
                ('processing_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('context_data', models.JSONField(default=dict, help_text='Full execution context')),
                ('result_data', models.JSONField(default=dict, help_text='Execution results')),
                ('error_details', models.TextField(blank=True, null=True)),
                ('learning_insights', models.JSONField(default=list, help_text='Generated insights')),
                ('properties_processed', models.IntegerField(blank=True, null=True)),
                ('processing_rate', models.FloatField(blank=True, help_text='Properties per second', null=True)),
                ('success_rate', models.FloatField(blank=True, help_text='Success percentage', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_context', models.TextField(blank=True, null=True)),
                ('business_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_records', to='ai_workers.businessaiworker')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business_worker', 'execution_status'], name='ai_workers__busines_1eee40_idx'), models.Index(fields=['strategy_used', 'execution_time'], name='ai_workers__strateg_ef851b_idx'), models.Index(fields=['file_size', 'processing_rate'], name='ai_workers__file_si_25003e_idx')],
            },
        ),
    ]
