# Generated by Django 4.2.19 on 2025-07-15 11:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ai_property_manager', '0009_temporarymedia_extracted_property_name_and_more'),
        ('ai_workers', '0004_aiworkerlearningrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('monthly_summary', 'Monthly Summary'), ('payment_status', 'Payment Status Report'), ('overdue_report', 'Overdue Payments Report'), ('late_fee_report', 'Late Fee Report'), ('annual_summary', 'Annual Summary'), ('tenant_profile', 'Tenant Financial Profile'), ('collection_analysis', 'Collection Analysis')], max_length=30)),
                ('report_period_start', models.DateField()),
                ('report_period_end', models.DateField()),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.CharField(default='AI System', max_length=100)),
                ('report_data', models.JSONField()),
                ('summary_stats', models.JSONField(default=dict)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('is_automated', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-generated_date'],
            },
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_address', models.CharField(max_length=500)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lease_start', models.DateField()),
                ('lease_end', models.DateField()),
                ('rent_due_day', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('late_fee_grace_days', models.IntegerField(default=5)),
                ('lease_terms', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_property_manager.propertylisting')),
            ],
            options={
                'ordering': ['-lease_start'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact', models.JSONField(blank=True, default=dict)),
                ('tenant_since', models.DateField()),
                ('payment_preferences', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(choices=[('upcoming', 'Upcoming Payment'), ('due_today', 'Due Today'), ('overdue', 'Overdue Payment'), ('late_fee_notice', 'Late Fee Notice')], max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('message_content', models.TextField()),
                ('delivery_method', models.CharField(default='email', max_length=20)),
                ('response_received', models.BooleanField(default=False)),
                ('response_content', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='ai_workers.lease')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='ai_workers.tenant')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_type', models.CharField(choices=[('rent', 'Rent Payment'), ('late_fee', 'Late Fee'), ('security_deposit', 'Security Deposit'), ('maintenance', 'Maintenance Fee'), ('utility', 'Utility Payment'), ('other', 'Other')], default='rent', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('check', 'Check'), ('cash', 'Cash'), ('money_order', 'Money Order'), ('online', 'Online Payment'), ('other', 'Other')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('processed_by', models.CharField(default='AI System', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ai_workers.lease')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ai_workers.tenant')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lease',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='ai_workers.tenant'),
        ),
        migrations.CreateModel(
            name='LateFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_payment_due', models.DateField()),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('days_late', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('waived', 'Waived'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('applied_date', models.DateField(blank=True, null=True)),
                ('waived_date', models.DateField(blank=True, null=True)),
                ('waived_reason', models.TextField(blank=True)),
                ('waived_by', models.CharField(blank=True, max_length=100)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_fees', to='ai_workers.lease')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='late_fees_paid', to='ai_workers.payment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_fees', to='ai_workers.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
