# Generated by Django 4.2.19 on 2025-02-11 21:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('house', 'House'), ('land', 'Land'), ('apartment', 'Apartment'), ('commercial', 'Commercial Property'), ('other', 'Other')], max_length=50)),
                ('listing_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('lease', 'For Lease')], default='sale', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('pending', 'Pending'), ('rented', 'Rented')], default='available', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('location', models.CharField(max_length=255)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, help_text='Area in square meters', null=True)),
                ('features', models.JSONField(blank=True, default=dict, help_text='Extra property details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
