# Generated by Django 4.2.19 on 2025-02-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_property_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='property_category',
            field=models.CharField(choices=[('Luxury', 'Luxury'), ('Standard', 'Standard'), ('Basic', 'Basic')], default='Basic', max_length=50),
        ),
    ]
