# Generated by Django 4.2.19 on 2025-02-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_property_manager', '0002_propertylisting_is_suspicious_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='average_market_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='is_overpriced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='is_underpriced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='price_deviation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='suggested_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
