# Generated by Django 4.2.19 on 2025-02-13 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_property_manager', '0003_propertylisting_average_market_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='property_media/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document')], default='image', max_length=10)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='ai_property_manager.propertylisting')),
            ],
        ),
    ]
