# Generated by Django 4.2.19 on 2025-02-13 11:32

import ai_workers.ai_property_manager.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ai_property_manager', '0004_propertymedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymedia',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='file',
            field=models.FileField(upload_to=ai_workers.ai_property_manager.models.unique_media_filename),
        ),
    ]
