# Generated by Django 4.2.19 on 2025-02-14 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_property_manager', '0005_propertymedia_uploaded_at_alter_propertymedia_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='temporary_media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('matched_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_property_manager.propertylisting')),
            ],
        ),
    ]
