# Generated by Django 4.2.19 on 2025-02-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_property_manager', '0006_temporarymedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarymedia',
            name='filename_hash',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
