# Generated by Django 4.2.19 on 2025-02-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_property_manager', '0007_temporarymedia_filename_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarymedia',
            name='filename_hash',
        ),
        migrations.RemoveField(
            model_name='temporarymedia',
            name='matched_property',
        ),
        migrations.AddField(
            model_name='temporarymedia',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='temporarymedia',
            name='title_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
