# Generated by Django 4.2.19 on 2025-02-15 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_property_manager', '0008_remove_temporarymedia_filename_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarymedia',
            name='extracted_property_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='temporarymedia',
            name='matched_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_property_manager.propertylisting'),
        ),
    ]
