# Generated by Django 4.2.19 on 2025-02-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_skills_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('entry', 'Entry Level'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], help_text='Only applicable for freelancers', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='workload',
            field=models.IntegerField(default=0),
        ),
    ]
