# Generated by Django 4.2.19 on 2025-02-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_completed_tasks_user_experience_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='budget_match',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='rating_score',
            field=models.FloatField(default=0.0),
        ),
    ]
