# Generated by Django 4.2.19 on 2025-02-10 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_budget_match_user_rating_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='budget_match',
        ),
    ]
