# Generated by Django 4.2.18 on 2025-01-19 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIEmployer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('job_preferences', models.TextField(help_text='Define job types or skills (e.g., Data Entry, Marketing).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('industry_type', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('required_skills', models.CharField(help_text='Comma-separated skills required (e.g., Python, Excel).', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_assigned', models.BooleanField(default=False)),
                ('ai_employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='business.aiemployer')),
            ],
        ),
        migrations.AddField(
            model_name='aiemployer',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_employer', to='business.business'),
        ),
    ]
