# Generated by Django 4.2.19 on 2025-02-10 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEmployerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_assign', models.BooleanField(default=True)),
                ('allow_override', models.BooleanField(default=True)),
                ('prioritize_low_cost', models.BooleanField(default=False)),
                ('prioritize_fast_response', models.BooleanField(default=False)),
                ('prioritize_experience', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
