# Generated by Django 4.2.18 on 2025-01-20 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiemployer',
            name='ai_employer_type',
            field=models.CharField(choices=[('freelancer', 'Freelancer'), ('company', 'Company')], default='company', max_length=100),
        ),
        migrations.AddField(
            model_name='aiemployer',
            name='industry_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aiemployer',
            name='joining_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aiemployer',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiemployer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=50),
        ),
    ]
