# Generated by Django 4.2.19 on 2025-02-10 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0002_aiemployersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.OneToOneField(blank=True, help_text='The user who owns this business.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL),
        ),
    ]
