# Generated by Django 4.2.19 on 2025-02-10 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_business_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(choices=[('tech', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('marketing', 'Marketing'), ('other', 'Other')], max_length=50)),
                ('job_role', models.CharField(choices=[('data_entry', 'Data Entry'), ('design', 'Design'), ('writing', 'Writing'), ('development', 'Development'), ('other', 'Other')], max_length=50)),
                ('complexity', models.CharField(choices=[('simple', 'Simple'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='business.taskcategory'),
        ),
    ]
