# Generated by Django 4.2.19 on 2025-02-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_taskcategory_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='budget',
            field=models.FloatField(default=0.0),
        ),
    ]
