# Generated by Django 4.2.19 on 2025-02-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_task_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='payment',
        ),
        migrations.AddField(
            model_name='aiemployer',
            name='past_tasks',
            field=models.JSONField(blank=True, help_text='AI memory of previously generated and completed tasks.', null=True),
        ),
        migrations.AddField(
            model_name='aiemployer',
            name='priority_focus',
            field=models.CharField(blank=True, help_text='Which business goal should AI prioritize? (e.g., Marketing, Sales, Customer Support)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiemployer',
            name='task_generation_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('semi_automatic', 'Semi-Automatic'), ('fully_automatic', 'Fully Automatic')], default='semi_automatic', help_text='How aggressively AI should generate tasks.', max_length=50),
        ),
        migrations.AddField(
            model_name='business',
            name='business_goals',
            field=models.TextField(blank=True, help_text="Describe the company's goals and long-term vision.", null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='daily_operations',
            field=models.JSONField(blank=True, help_text='List of daily business operations and responsibilities.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='goal_alignment',
            field=models.CharField(blank=True, help_text='Which business goal does this task support?', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='urgency',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2, help_text='How urgent is this task?'),
        ),
    ]
