# Generated by Django 4.2.19 on 2025-02-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_remove_task_payment_aiemployer_past_tasks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='budget',
            field=models.CharField(blank=True, default=0.0, max_length=255, null=True),
        ),
    ]
