# Generated by Django 4.2.19 on 2025-02-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_task_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='budget',
            field=models.FloatField(default=0.0),
        ),
    ]
